laravel/app/routes.php
<?php

Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('home', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::post('cadastroNewsletter', array('as' => 'cadastroNewsletter', 'uses' => 'HomeController@cadastro'));
Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

Route::get('imprensa', array('as' => 'imprensa', 'uses' => 'ImprensaController@index'));
Route::get('perguntas-frequentes', array('as' => 'perguntasfrequentes', 'uses' => 'PerguntasFrequentesController@index'));

Route::get('quem-somos', array('as' => 'quemsomos', 'uses' => 'QuemSomosController@index'));
Route::get('equipe', array('as' => 'equipe', 'uses' => 'EquipeController@index'));
Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));
Route::post('enviarContato',  array('as' => 'enviarContato', 'uses' => 'ContatoController@enviar'));

Route::get('enquetes', array('as' => 'enquetes', 'uses' => 'EnquetesController@index'));
Route::get('enquetes/resultados/{dia?}/{mes?}/{ano?}/{id?}', array('as' => 'resultados', 'uses' => 'EnquetesController@resultados'));
Route::post('computarVoto', array('as' => 'votar', 'uses' => 'EnquetesController@votar'));

Route::get('noticias', array('as' => 'textos.noticias', 'uses' => 'TextosController@noticias'));
Route::get('noticias/{slug?}', array('as' => 'textos.noticias.detalhes', 'uses' => 'TextosController@detalhes'));
Route::get('reportagens', array('as' => 'textos.reportagens', 'uses' => 'TextosController@reportagens'));
Route::get('reportagens/{slug?}', array('as' => 'textos.reportagens.detalhes', 'uses' => 'TextosController@detalhes'));
Route::get('entrevistas', array('as' => 'textos.entrevistas', 'uses' => 'TextosController@entrevistas'));
Route::get('entrevistas/{slug?}', array('as' => 'textos.entrevistas.detalhes', 'uses' => 'TextosController@detalhes'));
Route::get('eventos', array('as' => 'textos.eventos', 'uses' => 'TextosController@eventos'));
Route::get('eventos/{slug?}', array('as' => 'textos.eventos.detalhes', 'uses' => 'TextosController@detalhes'));
Route::get('artigos', array('as' => 'textos.artigos', 'uses' => 'TextosController@artigos'));
Route::get('artigos/{slug?}', array('as' => 'textos.artigos.detalhes', 'uses' => 'TextosController@detalhes'));
Route::get('dicas', array('as' => 'textos.dicas', 'uses' => 'TextosController@dicas'));
Route::get('dicas/{slug?}', array('as' => 'textos.dicas.detalhes', 'uses' => 'TextosController@detalhes'));
Route::get('pesquisas', array('as' => 'textos.pesquisas', 'uses' => 'TextosController@pesquisas'));
Route::get('pesquisas/{slug?}', array('as' => 'textos.pesquisas.detalhes', 'uses' => 'TextosController@detalhes'));
Route::any('busca/{termo?}', array('as' => 'busca', 'uses' => 'TextosController@busca'));
Route::post('compartilhar', array('uses' => 'TextosController@compartilhar'));

Route::get('politica-de-privacidade', function(){
	\View::share('contatoLayout', Contato::first());
	\View::share('bannerInferior', BannerInferior::first());
	\View::share('politica', PoliticaPrivacidade::first());
	\View::share('bannerInferior', BannerInferior::ordenado());

	return \View::make('frontend.politica-privacidade.index');
});

Route::any('mais-recentes', function(){
	$textos = \Textos::orderBy('data_publicacao', 'DESC')->limit(5)->get();
	foreach ($textos as $key => $value) {
		$value->link = 'http://www.metanews.com.br/'.$value->categoria->slug.'/'.$value->slug;
		$value->capa_grande = 'http://www.metanews.com.br/assets/images/textos/capas/grande/'.$value->capa;
		$value->capa_pequena = 'http://www.metanews.com.br/assets/images/textos/capas/pequena/'.$value->capa;
		$value->titulo_categoria = $value->categoria->titulo;
	}
	return Response::json($textos);
});

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));


Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
	Route::get('downloadCadastros', array('as' => 'painel.downloadCadastros', function(){

    	$filename = 'cadastros_'.date('d-m-Y-H-i-s');

		Excel::create($filename, function($excel) {
		    $excel->sheet('Usuários Cadastrados', function($sheet) {
		        $sheet->fromModel(\Cadastro::select('nome', 'email')->orderBy('nome')->get());
		    });
		})->download('csv');
    }));

	Route::post('pegarTextos', function(){
		$categoria = TextosCategorias::where('slug', '=', \Input::get('slug_categoria'))->first();
		return $categoria->textos->toJson();
	});

	Route::get('ativarEnquete/{id_enquete}', function($id_enquete){
		$todas = \EnquetePergunta::all();
		foreach ($todas as $key => $value) {
			$value->ativa = '0';
			$value->save();
		}
		$enquete = \EnquetePergunta::find($id_enquete);
		$enquete->ativa = '1';
		$enquete->save();
		return Redirect::back();
	});

    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('banners', 'Painel\BannersController');
	Route::resource('cadastros', 'Painel\CadastrosController');
	Route::resource('quemsomos', 'Painel\QuemSomosController');
	Route::resource('equipe', 'Painel\EquipeController');
	Route::resource('contato', 'Painel\ContatoController');
	Route::resource('enqueteperguntas', 'Painel\EnquetePerguntasController');
	Route::resource('textos', 'Painel\TextosController');
	Route::resource('destaques', 'Painel\DestaquesController');
	Route::resource('bannerinferior', 'Painel\BannerInferiorController');
	Route::resource('textosimagens', 'Painel\TextosImagensController');
	Route::resource('compartilhamentos', 'Painel\CompartilhamentosController');
	Route::resource('imprensa', 'Painel\ImprensaController');
	Route::resource('politica', 'Painel\PoliticaController');
	Route::resource('perguntasfrequentes/categorias', 'Painel\PerguntasFrequentesCategoriasController');
	Route::resource('perguntasfrequentes', 'Painel\PerguntasFrequentesController');
//NOVASROTASDOPAINEL//
});

laravel/app/controllers/painel/TextosImagensController.php
<?php

namespace Painel;

use \View, \Input, \Str, \Session, \Redirect, \Hash, \Thumb, \Tools, \File, \TextosImagem, \Textos;

class TextosImagensController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	protected $limiteInsercao = false;

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$id_texto = Input::get('id_texto');

		$this->layout->content = View::make('backend.textosimagens.index')->with('texto', Textos::find($id_texto));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$id_texto = Input::get('textos_id');

		$this->layout->content = View::make('backend.textosimagens.form')->with('texto', Textos::find($id_texto));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new TextosImagem;

		$t = date('YmdHis');
		$imagem = Thumb::make('imagem', 800, null, 'textosimagens/', $t);
		if($imagem) $object->imagem = $imagem;
		Thumb::make('imagem', 110, 110, 'textosimagens/thumbs/', $t);

		$object->textos_id = Input::get('textos_id');

		try {

			$object->save();

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Imagem inserida com sucesso.');
			return Redirect::route('painel.textosimagens.index', array('id_texto' => $object->textos_id));

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Imagem!'));	

		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('backend.textosimagens.edit')->with('registro', TextosImagem::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = TextosImagem::find($id);

		$t = date('YmdHis');
		$imagem = Thumb::make('imagem', 800, null, 'textosimagens/', $t);
		if($imagem) $object->imagem = $imagem;
		Thumb::make('imagem', 110, 110, 'textosimagens/thumbs/', $t);

		try {

			$object->save();
			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Imagem alterada com sucesso.');
			return Redirect::route('painel.textosimagens.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Imagem!'));

		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = TextosImagem::find($id);
		$id_parent = $object->textos_id;
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Imagem removida com sucesso.');

		return Redirect::route('painel.textosimagens.index', array('id_texto' => $id_parent));
	}

}

laravel/app/views/backend/textosimagens/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Editar Imagem
        </h2>  

		{{ Form::open( array('route' => array('painel.textosimagens.update', $registro->id), 'files' => true, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	


				<div class="form-group">
					@if($registro->imagem)
						Imagem Atual<br>
						<img src="assets/images/textosimagens/{{$registro->imagem}}"><br>
					@endif
					<label for="inputImagem">Trocar Imagem</label>
					<input type="file" class="form-control" id="inputImagem" name="imagem">
				</div>
				

				<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

				<a href="{{URL::route('painel.textosimagens.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/textosimagens/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Imagem à galeria do Texto - {{$texto->titulo}}
        </h2>  

		<form action="{{URL::route('painel.textosimagens.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif


				<div class="form-group">
					<label for="inputImagem">Imagem</label>
					<input type="file" class="form-control" id="inputImagem" name="imagem" required>
				</div>
				
				<input type="hidden" name="textos_id" value="{{$texto->id}}">

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.textosimagens.index', array('id_texto' => $texto->id))}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/textosimagens/index.blade.php
@section('conteudo')

<div class="container">

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <h2>
        Imagens do Texto - {{$texto->titulo}} <a href='{{ URL::route('painel.textosimagens.create', array('textos_id' => $texto->id)) }}' class='btn btn-success btn-sm pull-right'><span class='glyphicon glyphicon-plus-sign'></span> Adicionar Imagem</a>
    </h2>

    <a href="{{URL::route('painel.textos.index', array('categoria' => $texto->categoria->slug))}}" class="btn btn-default btn-sm">&larr; voltar</a>

    <table class='table table-striped table-bordered table-hover table-sortable' data-tabela='textos_imagens'>

        <thead>
            <tr>
                <th>Ordenar</th>
				<th>Imagem</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($texto->imagens as $registro)

            <tr class="tr-row" id="row_{{ $registro->id }}">
                <td class='move-actions'><a href='#' class='btn btn-info btn-move btn-sm'>mover</a></td>
				<td><img src='assets/images/textosimagens/thumbs/{{ $registro->imagem }}' style='max-width:150px'></td>
                <td class="crud-actions">
                    {{ Form::open(array('route' => array('painel.textosimagens.destroy', $registro->id), 'method' => 'delete')) }}
						<button type='submit' class='btn btn-danger btn-sm btn-delete'>excluir</button>
					{{ Form::close() }}                    
                </td>
            </tr>

        @endforeach
        </tbody>

    </table>

    
</div>

@stop