laravel/app/routes.php
<?php

Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('home', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::post('cadastroNewsletter', array('as' => 'cadastroNewsletter', 'uses' => 'HomeController@cadastro'));
Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

Route::get('imprensa', array('as' => 'imprensa', 'uses' => 'ImprensaController@index'));
Route::get('perguntas-frequentes', array('as' => 'perguntasfrequentes', 'uses' => 'PerguntasFrequentesController@index'));

Route::get('quem-somos', array('as' => 'quemsomos', 'uses' => 'QuemSomosController@index'));
Route::get('equipe', array('as' => 'equipe', 'uses' => 'EquipeController@index'));
Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));
Route::post('enviarContato',  array('as' => 'enviarContato', 'uses' => 'ContatoController@enviar'));

Route::get('enquetes', array('as' => 'enquetes', 'uses' => 'EnquetesController@index'));
Route::get('enquetes/resultados/{dia?}/{mes?}/{ano?}/{id?}', array('as' => 'resultados', 'uses' => 'EnquetesController@resultados'));
Route::post('computarVoto', array('as' => 'votar', 'uses' => 'EnquetesController@votar'));

Route::get('noticias', array('as' => 'textos.noticias', 'uses' => 'TextosController@noticias'));
Route::get('noticias/{slug?}', array('as' => 'textos.noticias.detalhes', 'uses' => 'TextosController@detalhes'));
Route::get('reportagens', array('as' => 'textos.reportagens', 'uses' => 'TextosController@reportagens'));
Route::get('reportagens/{slug?}', array('as' => 'textos.reportagens.detalhes', 'uses' => 'TextosController@detalhes'));
Route::get('entrevistas', array('as' => 'textos.entrevistas', 'uses' => 'TextosController@entrevistas'));
Route::get('entrevistas/{slug?}', array('as' => 'textos.entrevistas.detalhes', 'uses' => 'TextosController@detalhes'));
Route::get('eventos', array('as' => 'textos.eventos', 'uses' => 'TextosController@eventos'));
Route::get('eventos/{slug?}', array('as' => 'textos.eventos.detalhes', 'uses' => 'TextosController@detalhes'));
Route::get('artigos', array('as' => 'textos.artigos', 'uses' => 'TextosController@artigos'));
Route::get('artigos/{slug?}', array('as' => 'textos.artigos.detalhes', 'uses' => 'TextosController@detalhes'));
Route::get('dicas', array('as' => 'textos.dicas', 'uses' => 'TextosController@dicas'));
Route::get('dicas/{slug?}', array('as' => 'textos.dicas.detalhes', 'uses' => 'TextosController@detalhes'));
Route::get('pesquisas', array('as' => 'textos.pesquisas', 'uses' => 'TextosController@pesquisas'));
Route::get('pesquisas/{slug?}', array('as' => 'textos.pesquisas.detalhes', 'uses' => 'TextosController@detalhes'));
Route::any('busca/{termo?}', array('as' => 'busca', 'uses' => 'TextosController@busca'));
Route::post('compartilhar', array('uses' => 'TextosController@compartilhar'));

Route::get('politica-de-privacidade', function(){
	\View::share('contatoLayout', Contato::first());
	\View::share('bannerInferior', BannerInferior::first());
	\View::share('politica', PoliticaPrivacidade::first());
	\View::share('bannerInferior', BannerInferior::ordenado());

	return \View::make('frontend.politica-privacidade.index');
});

Route::any('mais-recentes', function(){
	$textos = \Textos::orderBy('data_publicacao', 'DESC')->limit(5)->get();
	foreach ($textos as $key => $value) {
		$value->link = 'http://www.metanews.com.br/'.$value->categoria->slug.'/'.$value->slug;
		$value->capa_grande = 'http://www.metanews.com.br/assets/images/textos/capas/grande/'.$value->capa;
		$value->capa_pequena = 'http://www.metanews.com.br/assets/images/textos/capas/pequena/'.$value->capa;
		$value->titulo_categoria = $value->categoria->titulo;
	}
	return Response::json($textos);
});

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));


Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
	Route::get('downloadCadastros', array('as' => 'painel.downloadCadastros', function(){

    	$filename = 'cadastros_'.date('d-m-Y-H-i-s');

		Excel::create($filename, function($excel) {
		    $excel->sheet('Usuários Cadastrados', function($sheet) {
		        $sheet->fromModel(\Cadastro::select('nome', 'email')->orderBy('nome')->get());
		    });
		})->download('csv');
    }));

	Route::post('pegarTextos', function(){
		$categoria = TextosCategorias::where('slug', '=', \Input::get('slug_categoria'))->first();
		return $categoria->textos->toJson();
	});

	Route::get('ativarEnquete/{id_enquete}', function($id_enquete){
		$todas = \EnquetePergunta::all();
		foreach ($todas as $key => $value) {
			$value->ativa = '0';
			$value->save();
		}
		$enquete = \EnquetePergunta::find($id_enquete);
		$enquete->ativa = '1';
		$enquete->save();
		return Redirect::back();
	});

    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('banners', 'Painel\BannersController');
	Route::resource('cadastros', 'Painel\CadastrosController');
	Route::resource('quemsomos', 'Painel\QuemSomosController');
	Route::resource('equipe', 'Painel\EquipeController');
	Route::resource('contato', 'Painel\ContatoController');
	Route::resource('enqueteperguntas', 'Painel\EnquetePerguntasController');
	Route::resource('textos', 'Painel\TextosController');
	Route::resource('destaques', 'Painel\DestaquesController');
	Route::resource('bannerinferior', 'Painel\BannerInferiorController');
	Route::resource('textosimagens', 'Painel\TextosImagensController');
	Route::resource('compartilhamentos', 'Painel\CompartilhamentosController');
	Route::resource('imprensa', 'Painel\ImprensaController');
	Route::resource('politica', 'Painel\PoliticaController');
	Route::resource('perguntasfrequentes/categorias', 'Painel\PerguntasFrequentesCategoriasController');
	Route::resource('perguntasfrequentes', 'Painel\PerguntasFrequentesController');
//NOVASROTASDOPAINEL//
});

laravel/app/views/backend/templates/index.blade.php
<!DOCTYPE html>
<html lang="pt-BR" class="no-js">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="robots" content="index, nofollow" />
    <meta name="author" content="Trupe Design" />
    <meta name="copyright" content="2013 Trupe Design" />
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <title>Meta News - Painel Administrativo</title>
	<meta name="description" content="">
    <meta name="keywords" content="" />

	<base href="{{ url() }}/">
	<script>var BASE = "{{ url() }}"</script>

	<?=Assets::CSS(array(
		'vendor/reset-css/reset',
		'css/fontface/stylesheet',
		'vendor/jquery-ui/themes/base/jquery-ui',
		'vendor/bootstrap/dist/css/bootstrap.min',
		'vendor/bootstrap/dist/css/bootstrap-theme.min',
		'css/painel/painel'
	))?>

	@if(isset($css))
		<?=Assets::CSS(array($css))?>
	@endif

	<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="assets/vendor/jquery/dist/jquery.min.js"><\/script>')</script>

	@if(App::environment()=='local')
		<?=Assets::JS(array('js/vendor/modernizr/modernizr', 'vendor/less.js/dist/less-1.6.2.min'))?>
	@else
		<?=Assets::JS(array('js/vendor/modernizr/modernizr'))?>
	@endif

</head>
	<body @if(Route::currentRouteName() == 'painel.login') class="body-painel-login" @else class="body-painel" @endif >

		@if(Route::currentRouteName() != 'painel.login')

			<nav class="navbar navbar-default">
				<div class="navbar-inner">
					<a href="{{URL::route('painel.home')}}" title="Página Inicial" class="navbar-brand">Meta News</a>

					<ul class="nav navbar-nav">

						<li @if(str_is('painel.home*', Route::currentRouteName())) class="active" @endif >
							<a href="{{URL::route('painel.home')}}" title="Início">Início</a>
						</li>

						<li class="dropdown @if(str_is('painel.banne*', Route::currentRouteName())) active @endif ">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Home <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="{{URL::route('painel.banners.index')}}" title="Notícias">Banners</a></li>
								<li><a href="{{URL::route('painel.bannerinferior.index')}}" title="Eventos">Banner Inferior</a></li>
							</ul>
						</li>

						<li @if(str_is('painel.quemsomos*', Route::currentRouteName())) class="active" @endif >
							<a href="{{URL::route('painel.quemsomos.index')}}" title="Quem Somos">Quem Somos</a>
						</li>

						<li @if(str_is('painel.equipe*', Route::currentRouteName())) class="active" @endif >
							<a href="{{URL::route('painel.equipe.index')}}" title="Equipe">Equipe</a>
						</li>

						<li @if(str_is('painel.imprensa*', Route::currentRouteName())) class="active" @endif >
							<a href="{{URL::route('painel.imprensa.index')}}" title="Imprensa">Imprensa</a>
						</li>

						<li @if(str_is('painel.perguntasfrequentes*', Route::currentRouteName())) class="active" @endif >
							<a href="{{URL::route('painel.perguntasfrequentes.index')}}" title="Perguntas Frequentes">Perguntas Frequentes</a>
						</li>

						<li @if(str_is('painel.contato*', Route::currentRouteName())) class="active" @endif >
							<a href="{{URL::route('painel.contato.index')}}" title="Contato">Contato</a>
						</li>

						<li @if(str_is('painel.enquete*', Route::currentRouteName())) class="active" @endif >
							<a href="{{URL::route('painel.enqueteperguntas.index')}}" title="Enquetes">Enquetes</a>
						</li>

						<li class="dropdown @if(str_is('painel.textos*', Route::currentRouteName()) || str_is('painel.destaques*', Route::currentRouteName()) || str_is('painel.compartilhamentos*', Route::currentRouteName())) active @endif ">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Textos <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="{{URL::route('painel.textos.index', array('categoria' => 'noticias'))}}" title="Notícias">Notícias</a></li>
								<li><a href="{{URL::route('painel.textos.index', array('categoria' => 'reportagens'))}}" title="Reportagens">Reportagens</a></li>
								<li><a href="{{URL::route('painel.textos.index', array('categoria' => 'entrevistas'))}}" title="Entrevistas">Entrevistas</a></li>
								<li><a href="{{URL::route('painel.textos.index', array('categoria' => 'eventos'))}}" title="Eventos">Eventos</a></li>
								<li><a href="{{URL::route('painel.textos.index', array('categoria' => 'artigos'))}}" title="Artigos">Artigos</a></li>
								<li><a href="{{URL::route('painel.textos.index', array('categoria' => 'dicas'))}}" title="Dicas">Dicas</a></li>
								<li><a href="{{URL::route('painel.textos.index', array('categoria' => 'pesquisas'))}}" title="Pesquisas">Pesquisas</a></li>
								<li role="presentation" class="divider"></li>
								<li><a href="{{URL::route('painel.destaques.index')}}" title="Destaques da Home">Destaques da Home</a></li>
								<li role="presentation" class="divider"></li>
								<li><a href="{{URL::route('painel.compartilhamentos.index')}}" title="Compartilhamentos">Compartilhamentos</a></li>
							</ul>
						</li>

						<li @if(str_is('painel.politica*', Route::currentRouteName())) class="active" @endif >
							<a href="{{URL::route('painel.politica.index')}}" title="Política de Privacidade">Política de Privacidade</a>
						</li>

						<li class="dropdown @if(str_is('painel.usuarios*', Route::currentRouteName())) active @endif ">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Sistema <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="{{URL::route('painel.cadastros.index')}}" title="Cadastros de Newsletter">Cadastros de Newsletter</a></li>
								<li><a href="{{URL::route('painel.usuarios.index')}}" title="Usuários do Painel">Usuários</a></li>
								<li><a href="{{URL::route('painel.off')}}" title="Logout">Logout</a></li>
							</ul>
						</li>

					</ul>
				</div>
			</nav>

		@endif

		<div class="main {{ 'main-'.str_replace('.', '-', Route::currentRouteName()) }}">
			@yield('conteudo')
		</div>

		<footer>
			<div class="container">
				<a href="http://www.trupe.net" target="_blank" title="Criação de Sites : Trupe Agência Criativa">© Criação de Sites : Trupe Agência Criativa</a>
			</div>
		</footer>

		@if(Route::currentRouteName() == 'painel.login')
			<?=Assets::JS(array(
				'vendor/jquery-ui/ui/minified/jquery-ui.min',
				'vendor/bootbox/bootbox',
				'vendor/ckeditor/ckeditor',
				'vendor/ckeditor/adapters/jquery',
				'vendor/bootstrap/dist/js/bootstrap.min',
				'js/painel/login'
			))?>
		@else
			<?=Assets::JS(array(
				'vendor/jquery-ui/ui/minified/jquery-ui.min',
				'vendor/bootbox/bootbox',
				'vendor/ckeditor/ckeditor',
				'vendor/ckeditor/adapters/jquery',
				'vendor/bootstrap/dist/js/bootstrap.min',
				'js/painel/painel'
			))?>
		@endif

	</body>
</html>