laravel/app/routes.php
<?php

Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('home', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::post('cadastroNewsletter', array('as' => 'cadastroNewsletter', 'uses' => 'HomeController@cadastro'));
Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

Route::get('imprensa', array('as' => 'imprensa', 'uses' => 'ImprensaController@index'));
Route::get('perguntas-frequentes', array('as' => 'perguntasfrequentes', 'uses' => 'PerguntasFrequentesController@index'));

Route::get('quem-somos', array('as' => 'quemsomos', 'uses' => 'QuemSomosController@index'));
Route::get('equipe', array('as' => 'equipe', 'uses' => 'EquipeController@index'));
Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));
Route::post('enviarContato',  array('as' => 'enviarContato', 'uses' => 'ContatoController@enviar'));

Route::get('enquetes', array('as' => 'enquetes', 'uses' => 'EnquetesController@index'));
Route::get('enquetes/resultados/{dia?}/{mes?}/{ano?}/{id?}', array('as' => 'resultados', 'uses' => 'EnquetesController@resultados'));
Route::post('computarVoto', array('as' => 'votar', 'uses' => 'EnquetesController@votar'));

Route::get('noticias', array('as' => 'textos.noticias', 'uses' => 'TextosController@noticias'));
Route::get('noticias/{slug?}', array('as' => 'textos.noticias.detalhes', 'uses' => 'TextosController@detalhes'));
Route::get('reportagens', array('as' => 'textos.reportagens', 'uses' => 'TextosController@reportagens'));
Route::get('reportagens/{slug?}', array('as' => 'textos.reportagens.detalhes', 'uses' => 'TextosController@detalhes'));
Route::get('entrevistas', array('as' => 'textos.entrevistas', 'uses' => 'TextosController@entrevistas'));
Route::get('entrevistas/{slug?}', array('as' => 'textos.entrevistas.detalhes', 'uses' => 'TextosController@detalhes'));
Route::get('eventos', array('as' => 'textos.eventos', 'uses' => 'TextosController@eventos'));
Route::get('eventos/{slug?}', array('as' => 'textos.eventos.detalhes', 'uses' => 'TextosController@detalhes'));
Route::get('artigos', array('as' => 'textos.artigos', 'uses' => 'TextosController@artigos'));
Route::get('artigos/{slug?}', array('as' => 'textos.artigos.detalhes', 'uses' => 'TextosController@detalhes'));
Route::get('dicas', array('as' => 'textos.dicas', 'uses' => 'TextosController@dicas'));
Route::get('dicas/{slug?}', array('as' => 'textos.dicas.detalhes', 'uses' => 'TextosController@detalhes'));
Route::get('pesquisas', array('as' => 'textos.pesquisas', 'uses' => 'TextosController@pesquisas'));
Route::get('pesquisas/{slug?}', array('as' => 'textos.pesquisas.detalhes', 'uses' => 'TextosController@detalhes'));
Route::any('busca/{termo?}', array('as' => 'busca', 'uses' => 'TextosController@busca'));
Route::post('compartilhar', array('uses' => 'TextosController@compartilhar'));

Route::get('politica-de-privacidade', function(){
	\View::share('contatoLayout', Contato::first());
	\View::share('bannerInferior', BannerInferior::first());
	\View::share('politica', PoliticaPrivacidade::first());
	\View::share('bannerInferior', BannerInferior::ordenado());

	return \View::make('frontend.politica-privacidade.index');
});

Route::any('mais-recentes', function(){
	$textos = \Textos::orderBy('data_publicacao', 'DESC')->limit(5)->get();
	foreach ($textos as $key => $value) {
		$value->link = 'http://www.metanews.com.br/'.$value->categoria->slug.'/'.$value->slug;
		$value->capa_grande = 'http://www.metanews.com.br/assets/images/textos/capas/grande/'.$value->capa;
		$value->capa_pequena = 'http://www.metanews.com.br/assets/images/textos/capas/pequena/'.$value->capa;
		$value->titulo_categoria = $value->categoria->titulo;
	}
	return Response::json($textos);
});

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));


Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
	Route::get('downloadCadastros', array('as' => 'painel.downloadCadastros', function(){

    	$filename = 'cadastros_'.date('d-m-Y-H-i-s');

		Excel::create($filename, function($excel) {
		    $excel->sheet('Usuários Cadastrados', function($sheet) {
		        $sheet->fromModel(\Cadastro::select('nome', 'email')->orderBy('nome')->get());
		    });
		})->download('csv');
    }));

	Route::post('pegarTextos', function(){
		$categoria = TextosCategorias::where('slug', '=', \Input::get('slug_categoria'))->first();
		return $categoria->textos->toJson();
	});

	Route::get('ativarEnquete/{id_enquete}', function($id_enquete){
		$todas = \EnquetePergunta::all();
		foreach ($todas as $key => $value) {
			$value->ativa = '0';
			$value->save();
		}
		$enquete = \EnquetePergunta::find($id_enquete);
		$enquete->ativa = '1';
		$enquete->save();
		return Redirect::back();
	});

    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('banners', 'Painel\BannersController');
	Route::resource('cadastros', 'Painel\CadastrosController');
	Route::resource('quemsomos', 'Painel\QuemSomosController');
	Route::resource('equipe', 'Painel\EquipeController');
	Route::resource('contato', 'Painel\ContatoController');
	Route::resource('enqueteperguntas', 'Painel\EnquetePerguntasController');
	Route::resource('textos', 'Painel\TextosController');
	Route::resource('destaques', 'Painel\DestaquesController');
	Route::resource('bannerinferior', 'Painel\BannerInferiorController');
	Route::resource('textosimagens', 'Painel\TextosImagensController');
	Route::resource('compartilhamentos', 'Painel\CompartilhamentosController');
	Route::resource('imprensa', 'Painel\ImprensaController');
	Route::resource('politica', 'Painel\PoliticaController');
	Route::resource('perguntasfrequentes/categorias', 'Painel\PerguntasFrequentesCategoriasController');
	Route::resource('perguntasfrequentes', 'Painel\PerguntasFrequentesController');
//NOVASROTASDOPAINEL//
});

laravel/app/controllers/PerguntasFrequentesController.php
<?php

use \PerguntaFrequente, \PerguntaFrequenteCategoria;

class PerguntasFrequentesController extends BaseController {

    protected $layout = 'frontend.templates.index';

    public function index()
    {
        $registros = PerguntaFrequenteCategoria::with('perguntas')->ordenados()->get();
        $semCategoria = PerguntaFrequente::has('categoria', '<', 1)->ordenados()->get();

        $this->layout->with('pagetitle', 'Perguntas Frequentes');
        $this->layout->content = View::make('frontend.perguntasfrequentes.index')->with(compact('registros', 'semCategoria'));
    }

}

laravel/app/controllers/painel/PerguntasFrequentesController.php
<?php

namespace Painel;

use \View, \Input, \Session, \Redirect, \PerguntaFrequente, \PerguntaFrequenteCategoria;

class PerguntasFrequentesController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	protected $limiteInsercao = false;

	public function index()
	{
		$registros = PerguntaFrequente::with('categoria')->ordenados()->get();

		$this->layout->content = View::make('backend.perguntasfrequentes.index')->with(compact('registros'));
	}

	public function create()
	{
		$categorias = PerguntaFrequenteCategoria::ordenados()->lists('titulo', 'id');
		$this->layout->content = View::make('backend.perguntasfrequentes.form', compact('categorias'));
	}

	public function store()
	{
		$input = Input::all();

		try {

			PerguntaFrequente::create($input);

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Pergunta adicionada com sucesso.');
			return Redirect::route('painel.perguntasfrequentes.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao adicionar pergunta!'));

		}
	}

	public function edit($id)
	{
		$registro = PerguntaFrequente::findOrFail($id);
		$categorias = PerguntaFrequenteCategoria::ordenados()->lists('titulo', 'id');

		$this->layout->content = View::make('backend.perguntasfrequentes.edit')->with(compact('registro', 'categorias'));
	}

	public function update($id)
	{
		$object = PerguntaFrequente::find($id);
		$input  = Input::all();

		try {

			$object->update($input);

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Pergunta alterada com sucesso.');
			return Redirect::route('painel.perguntasfrequentes.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao alterar pergunta!'));

		}
	}

	public function destroy($id)
	{
		PerguntaFrequente::find($id)->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Pergunta removida com sucesso.');
		return Redirect::route('painel.perguntasfrequentes.index');
	}
}

laravel/app/views/backend/perguntasfrequentes/categorias/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Editar Categoria
        </h2>

		{{ Form::open( array('route' => array('painel.perguntasfrequentes.categorias.update', $registro->id), 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif

                <div class="form-group">
                    <label for="inputTitulo">Título</label>
                    <input type="text" class="form-control" id="inputTitulo" name="titulo" value="{{ $registro->titulo }}" required>
                </div>

				<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

				<a href="{{URL::route('painel.perguntasfrequentes.categorias.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>

@stop

laravel/app/views/backend/perguntasfrequentes/categorias/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Categoria
        </h2>

		<form action="{{URL::route('painel.perguntasfrequentes.categorias.store')}}" method="post">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif

		    	<div class="form-group">
		    		<label for="inputTitulo">Título</label>
					<input type="text" class="form-control" id="inputTitulo" name="titulo" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['titulo'] }}" @endif required>
		    	</div>

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.perguntasfrequentes.categorias.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>

@stop

laravel/app/views/backend/perguntasfrequentes/categorias/index.blade.php
@section('conteudo')

<div class="container">

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <a href="{{ URL::route('painel.perguntasfrequentes.index') }}" class="btn btn-default">&larr; Voltar para Perguntas Frequentes</a>

    <h2>
        Perguntas Frequentes / Categorias
        <a href='{{ URL::route('painel.perguntasfrequentes.categorias.create') }}' class='btn btn-success btn-sm pull-right'><span class='glyphicon glyphicon-plus-sign'></span> Adicionar Categoria</a>
    </h2>

    <table class='table table-striped table-bordered table-hover table-sortable' data-tabela='perguntas_frequentes_categorias'>

        <thead>
            <tr>
                <th>Ordenar</th>
				<th>Título</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)

            <tr class="tr-row" id="row_{{ $registro->id }}">
                <td class='move-actions'><a href='#' class='btn btn-info btn-move btn-sm'>mover</a></td>
				<td>{{ $registro->titulo }}</td>
                <td class="crud-actions">
                    <a href='{{ URL::route('painel.perguntasfrequentes.categorias.edit', $registro->id ) }}' class='btn btn-primary btn-sm'>editar</a>
						{{ Form::open(array('route' => array('painel.perguntasfrequentes.categorias.destroy', $registro->id), 'method' => 'delete')) }}
							<button type='submit' class='btn btn-danger btn-sm btn-delete'>excluir</button>
						{{ Form::close() }}
                </td>
            </tr>

        @endforeach
        </tbody>

    </table>


</div>

@stop